name: locked-room
region: nyc
services:
  - name: web
    github:
      repo: AxsolTools/locked
      branch: main
      deploy_on_push: true
    build_command: rm -rf node_modules package-lock.json && npm install && npm run build
    run_command: node dist/index.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    http_port: 5000
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
        scope: BUILD_TIME
      - key: HOUSE_WALLET_SECRET
        value: "3pRtqxssHfCxiVwPgfBspvVEhqCQbhmVtZp4gD6uEEvMkEYizU5NXYFwuzMTMqaUnj9sy8GbG5B9DmQwb9Y69yHB"
        scope: RUN_TIME
