name: locked-room
region: nyc
services:
  - name: web
    github:
      repo: AxsolTools/locked
      branch: main
      deploy_on_push: true
    build_command: rm -rf node_modules package-lock.json && npm install && npm run build
    run_command: node dist/index.js
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-1gb
    http_port: 5000
    envs:
      - key: NODE_ENV
        value: production
        scope: RUN_TIME
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
        scope: BUILD_TIME
      - key: PORT
        value: "5000"
      - key: SOLANA_RPC_URLS
        value: "https://mainnet.helius-rpc.com/?api-key=f7ed61b3-6e69-4ff8-b086-0f361e9dffb2"
      - key: HELIUS_API_KEY
        value: "f7ed61b3-6e69-4ff8-b086-0f361e9dffb2"
      - key: HELIUS_RPC_URL
        value: "https://mainnet.helius-rpc.com/?api-key=f7ed61b3-6e69-4ff8-b086-0f361e9dffb2"
      - key: LOCKED_TOKEN_MINT
        value: "B7tP6jNAcSmnvcuKsTFdvTAJHMkEQaXse8TMxoq2pump"
      - key: LOCKED_TOKEN_SYMBOL
        value: "NULL"
      - key: TOKEN_DECIMALS
        value: "9"
      - key: HOUSE_WALLET_SECRET
        type: SECRET
        value: "[246,132,204,248,210,226,245,128,124,202,121,34,158,131,205,43,194,88,35,137,145,168,175,205,35,227,152,117,250,149,52,173,138,3,143,36,13,116,153,222,236,13,195,89,253,82,196,156,78,146,224,32,88,240,192,206,232,141,137,97,187,186,129,21]"
      - key: DICE_ENABLED
        value: "true"
      - key: HOUSE_EDGE
        value: "1.5"
      - key: MIN_BET_AMOUNT
        value: "1"
      - key: MAX_BET_AMOUNT
        value: "10000"
      - key: MAX_PROFIT
        value: "5000"

